// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcgI9Uu25da_XOp9xAojnvjx-SToAlqeU',
    appId: '1:797834892606:web:167cf052de8f5300fdc86f',
    messagingSenderId: '797834892606',
    projectId: 'dbmagang-ec5dc',
    authDomain: 'dbmagang-ec5dc.firebaseapp.com',
    storageBucket: 'dbmagang-ec5dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX_HjFwXDwt3yW8oiyvVySPJeRJVO1Zaw',
    appId: '1:797834892606:android:64061cffd2355d52fdc86f',
    messagingSenderId: '797834892606',
    projectId: 'dbmagang-ec5dc',
    storageBucket: 'dbmagang-ec5dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmfSeZmt1XvVeoyIMsAOHceEw_gHiPKTE',
    appId: '1:797834892606:ios:b0b9a1596d7714e8fdc86f',
    messagingSenderId: '797834892606',
    projectId: 'dbmagang-ec5dc',
    storageBucket: 'dbmagang-ec5dc.appspot.com',
    iosBundleId: 'com.example.mkTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmfSeZmt1XvVeoyIMsAOHceEw_gHiPKTE',
    appId: '1:797834892606:ios:e89f1e98a64080dbfdc86f',
    messagingSenderId: '797834892606',
    projectId: 'dbmagang-ec5dc',
    storageBucket: 'dbmagang-ec5dc.appspot.com',
    iosBundleId: 'com.example.mkTutorial.RunnerTests',
  );
}
